One room for two adult
OlhaLushina/mimino pull request #13
Opened 2022-12-12 13:36 UTC by koltok

Привіт! Попередня версія.

2022-12-13 01:39 UTC, OlhaLushina requested changes
1) Навіщо ти в index.html додаєш секції готелю?
 <include src="./partials/pages/hotel/hero.html"></include>
      <include
        src="./partials/pages/hotel/one-room-luxe-for-two-adult.html"
      ></include>
      <include
        src="./partials/pages/hotel/one-room-for-three-adult.html"
      ></include>
      <include
        src="./partials/pages/hotel/one-room-for-two-adult.html"
      ></include>

2) В src/sass/pages/hotel/_one-room-for-two-adult.scss не треба прописувати .container, він у нас уже окремим компонентом є
3) @media screen and (min-width:414px) треба заміняти на @include mobile
4) @media screen and (min-width:1024px) треба заміняти на @include tablet
5) @media screen and (min-width:1280px) треба заміняти на @include desktop
6) .foto-room  - дай більш унікальну назву класу (foto - краще photo)
7) В src/sass/pages/hotel/_one-room-for-two-adult.scss не треба прописувати копії кнопок .btn-dark та інших. Вони ж у нас уже є

2022-12-13 10:42 UTC, koltok commented
Привіт, внесла зміни.
Щодо @include, то поки не змінювала, так як у мене вони не спрацьовують - зміню в останньому варіанту.
Контейнер також не бачить

2022-12-13 11:46 UTC, koltok commented
(Навіщо ти в index.html додаєш секції готелю?
<include
src="./partials/pages/hotel/one-room-luxe-for-two-adult.html"
<include
src="./partials/pages/hotel/one-room-for-three-adult.html"
<include
src="./partials/pages/hotel/one-room-for-two-adult.html")

Прибрала це з index.html  - перестало відображати сторінку (можливо вказаний не вірний шлях)?
Там сторінка hotel, а посилання - about hotel
<include src="./partials/pages/main/about-hotel.html"></include>

2022-12-13 12:38 UTC, OlhaLushina requested changes
1)  @media screen and (min-width:1280px) заміни на @include desktop
2) @media screen and (min-width:1024px) заміни на @include table
3) @media screen and (min-width:414px)  заміни на @include mobile
4) Навіщо ти додаєш картинки, ними ж Михайло  займався, чи він не всі додав?
5) Клас .container видали у себе зі стилів, він уже прописаний
6) У тебе не правильно підключені шрифти. Їх треба підключити зміними з файлу utils/_vars.scss. Наприклад, Міміно - це font-family: var(--logo-fonts);

2022-12-15 00:19 UTC, OlhaLushina approved these changes

2022-12-15 00:19 UTC, merged