Feature/hotel/one room for three adult slick 3
OlhaLushina/mimino pull request #16
Opened 2022-12-12 19:56 UTC by NataliiaRud

Олю,
Я закінчила секцію у всіх версіях БЕЗ СЛАЙДЕРУ.
1. Слайдер замінений на декоративний дів відповідної геометрії.
2. Верстка базована на падінгах 15-47-85рх (моб, таблет, десктоп відповідно) - для цього я внесла правила в свою версію контейнера падінги, поки Інга не виправить.
3. Гілка нова - всі зауваження по попередій я виправила.
4. Слайдер поки не виходить.

2022-12-13 02:22 UTC, OlhaLushina requested changes
1) Написи "Amet minim mollit non" і "MIMIHO" мають бути вирівняні по правому краю
2) Напис "ТРЬОХМІСНИЙ НОМЕР" і текст, що нижче мають бути вирівняні по лівому краю
3) Треба прибрати всі червоні обводки
4) Картинка для мобілки має бути 244 на 322
5) Для планшета картинка має вилазити вгору на 32px
6) У файл src/sass/components/_container.scss не треба вносити зміні, там уже прописаний клас .container
7) Треба видалити з файлу src/sass/pages/hotel/_one-room-for-three-adult.scss класи .section, .container. Вони стандартні для всіх і уже прописані
8) .pre-title, .btn-link, .btn - треба назвати більш оригінально, щоб не було повторів на сайті

2022-12-13 07:34 UTC, NataliiaRud commented
Олю всі рекомендації виконала

2022-12-13 09:45 UTC, NataliiaRud commented
Перенесла падінги в секцію.

2022-12-13 10:36 UTC, OlhaLushina requested changes
Тут дуже багато конфліктів. Тобі треба взяти нові оновлення з гілки main

2022-12-14 12:38 UTC, OlhaLushina requested changes
Твоя гілка перетирає існюючі файли. Краще візьми оновлення з гіті і створи нову гілку.

2022-12-16 01:23 UTC, closed without merging