1 room luxe for 2 adult by serhii rud
OlhaLushina/mimino pull request #17
Opened 2022-12-13 07:27 UTC by NataliiaRud

Олю, вітаю, це Сергій Рудь.
По технічним причинам змушений відправляти свою гілку з акаунту дружини - Наталії.
Слайдер не підключений - вставлена заглушка.

2022-12-13 11:56 UTC, OlhaLushina approved these changes
1) Картинка на десктопі має бути 460 на 574
2) Падінги вгорі і внизу треба брати з секції

2022-12-13 12:22 UTC, OlhaLushina requested changes
1) Кнопки на десктопі і планшеті мають бути праворуч, а не ліворуч
2) Картинка на мобілці має бути праворуч, а не ліворуч
3) Я залила з основної гілки твої правки, візьми з гіта оновлення

2022-12-13 15:30 UTC, NataliiaRud commented
Змістив зображення та кнопки як треба.

2022-12-14 12:29 UTC, OlhaLushina requested changes
Твої стилі ламають секцію "ТРЬОХМІСНИЙ НОМЕР", яку робила Наталя Рудь

2022-12-16 01:23 UTC, closed without merging